serverAddr = "hz.knogen.com"
serverPort = 7000
auth.token = "knogen"

[[proxies]]
name = "http_proxy"
type = "tcp"
remotePort = 23333
[proxies.plugin]
type = "http_proxy"

[[proxies]]
name = "socks5"
type = "tcp"
remotePort = 23334
[proxies.plugin]
type = "socks5"

